### ISSUE TITLE
Syntax error in repository name

### ISSUE THREAD

**Issue by derekstavis** [metal/metal-clipboard#1]
Looks like the repository name is missing an `o`, and that it wasn't intentional, as README displays the expected name. As the project is in early state it's the best time to fix it :stuck_out_tongue_winking_eye:

**Comment by eduardolundgren** [comment]
Good catch :)

**Comment by eduardolundgren** [comment]
Thanks.

**Comment by derekstavis** [comment]
yw! :+1:
