### ISSUE TITLE
Export ClipboardAction

### ISSUE THREAD

**Issue by robframpton** [metal/metal-clipboard#2]
Currently the ClipboardAction class isn't exported, which would be nice for situations where adding a delegate isn't ideal.

**Comment by vbence86** [comment]
I've addressed this in https://github.com/metal/metal-clipboard/pull/3

**Comment by jbalsas** [comment]
Hey @Robert-Frampton, as @vbence86 pointed out, we've exported it, but based on how coupled it is, I'm not sure that would be all you need.

Could you check and reopen and add a more concrete example otherwise?

Thanks!

**Comment by robframpton** [comment]
I think that's all we needed, so we should be good.
